#!/usr/bin/env python3

import fileinput

struct = False
func = False
for line in fileinput.input():
    line = line.removesuffix("\n")

    if line.startswith("type ") and line.endswith(" struct {"):
        struct = True
    elif struct and line.endswith("}"):
        struct = False
    elif line.startswith("func"):
        func = True
    elif line == "":
        func = False

    if struct:
        if not line.lstrip().startswith("//") or "Has unexported fields" in line:
            print(line)
    elif func:
        if not line.startswith("    "):
            print(line)
    else:
        print(line)
