#!/usr/bin/env python3

import fileinput
from collections import deque
from typing import Iterator
from typing import TypeVar

T = TypeVar("T")


def window(it: Iterator[T], size: int = 2) -> Iterator[list[T]]:
    if size < 2:
        raise ValueError("Window size must be at least 2")

    window: deque[T] = deque(maxlen=size)

    for _ in range(size):
        try:
            window.append(next(it))
        except StopIteration:
            return

    yield list(window)

    for item in it:
        window.append(item)
        yield list(window)


struct = False
trailing_comment = False
for line, next_line in window(fileinput.input()):
    line = line.removesuffix("\n")
    next_line = next_line.removesuffix("\n")

    if line.startswith("type ") and line.endswith(" struct {"):
        struct = True
    elif struct and line.endswith("}"):
        struct = False
    elif line.startswith("func"):
        trailing_comment = True
    elif next_line[:4].strip() != "":
        trailing_comment = False

    if line.strip().startswith("}"):
        trailing_comment = True

    if struct:
        if (
            line != ""
            and not line.lstrip().startswith("//")
            or line.endswith("Has unexported fields.")
            or next_line.endswith("Has unexported fields.")
        ):
            print(line)
    elif trailing_comment:
        if line != "" and not line.startswith("    "):
            print(line)
    else:
        print(line)
